sudo: required

services:
- docker

before_install:
- docker pull centos:7.4.1708

script:
- >
  docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo centos:7.4.1708
  bash -c
  "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
   yum install -y https://download.ceph.com/rpm-luminous/el7/noarch/ceph-release-1-1.el7.noarch.rpm &&
   mkdir -p /rpms &&
   yum remove -y python-chardet &&
   yum -y install --downloadonly --downloaddir=/rpms docker docker-python docker-compose python-chardet python-requests &&
   yum -y install --downloadonly --downloaddir=/rpms audit rsync jq git tcpdump nc bind-utils net-tools chrony &&
   yum -y install --downloadonly --downloaddir=/rpms ceph-deploy ceph ceph-radosgw rbd-nbd rbd-mirror open-vm-tools  nfs-utils && 
   yum -y install --downloadonly --downloaddir=/rpms kubernetes-cni-0.5.1-1 kubectl-1.8.6 kubelet-1.8.6 kubeadm-1.8.6
   yum install -y createrepo &&
   yum clean all &&
   createrepo /rpms"
- sudo chmod -R 755 ${PWD}/rpms
- docker build -t wisecloud/yum-repo:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wisecloud/yum-repo:$TRAVIS_BRANCH
